### ISSUE TITLE
Where is GetInfo() processed?

### ISSUE THREAD

**Issue by MattHamsay** [gordon-matt/elFinder.NetCore#1]
Hello,

I'm looking for the method that processes `cmdinfo`, and specifically for producing the link provided to `Link: star.png`.

![getinfo](https://user-images.githubusercontent.com/13993613/29626052-27b490fc-87f3-11e7-97c2-78d482e1680e.png)

When I click on the `GetInfo/Link` from the context menu, it opens up a new link that looks like:

```
http://localhost:53730/file/connector?folder=MyFolder&subFolder=&cmd=file&target=v1_XHN0YXIucG5n0
```

I am trying to change the behaviour so that clicking on the link will open up a new tab page with an absolute URL to the file. Using the same example above, ideally the link will be:

```
http://localhost:53730/files/myfolder/star.png
```

where the folder structure is:

```
wwwroot/
wwwroot/js/
wwwroot/Files/MyFolder/star.png
```

I will be running this on a trusted localhost server only, so there is zero concern with security.

Could someone please guide me to a method that is related to this?

I've looked at

```
elfinder.full.js
Root.cs
Connector.cs
FileSystemDriver.cs
FileController.cs
```

but unfortunately didn't have a luck, except this:

`elfinder.full.js.8713`
```
'cmdinfo'      : 'Get info',
```
`elfinder.full.js.13477 `
```
fm.request({
	data : {cmd : 'info', targets : hashes},
	preventDefault : true
})
```

Any helps or hints will be much appreciated.

**Comment by gordon-matt** [comment]
This project is only the ASP.NET Core backend for elFinder. I think your question should probably be asked at the repo for elFinder itself, which you can find here: [https://github.com/Studio-42/elFinder](https://github.com/Studio-42/elFinder)

**Comment by gordon-matt** [comment]
FYI - I have been doing quite a bit of work on this connector recently and looked into this issue a little further. If you get the latest version, you will find that the links are now to the absolute URLs and not something like `connector.php?cmd=file&target=HASH_TO_FILE_PATH` which it was before.
