### ISSUE TITLE
Invalid backend response.Error occurred on the server side.HTTP error 500.

### ISSUE THREAD

**Issue by cihangll** [gordon-matt/elFinder.NetCore#13]
Hi.
When I create a new file( *.txt), the file stays open and i am getting this error 

> Invalid backend response.Error occurred on the server side.HTTP error 500.
![image](https://user-images.githubusercontent.com/6229029/40303805-05c06036-5cfd-11e8-82fc-88ac3d570a62.png)

And this file stays open.When i want to open this file i am getting this error.
![image](https://user-images.githubusercontent.com/6229029/40303960-84f641ea-5cfd-11e8-8788-975ef813b806.png)

Other bug is;
Right click any file> into new folder option click > set folder name > ok.
Selected file is deleted and gives this error again
> Invalid backend response.Error occurred on the server side.HTTP error 500.

**Comment by cihangll** [comment]
When I change the file name i get same error and the file disappears.

**Comment by gordon-matt** [comment]
Thanks for letting me know. This should be fixed now. I have uploaded a new NuGet package, but it may take a little while before it's published. Please check and confirm everything works for you.

**Comment by cihangll** [comment]
Thank you for your time.I don't get error for new file and edit this file but still i am getting this error when i change file name, move file to another folder etc.There isn't error in version 1.02

**Comment by gordon-matt** [comment]
Yes, I could see the issues. There were a lot of changes recently to support other storage providers and it seems something broke in the process. I should have tested more thoroughly before releasing. Anyway, I have just fixed the issues I could see and uploaded a new version to NuGet. Please let me know if it's okay for you now. It seems fine here.

**Comment by cihangll** [comment]
Thank you for your time. 👍

**Comment by gordon-matt** [comment]
I assume that means you don't see anymore issues with it, right?

**Comment by cihangll** [comment]
Yes,thank you again.You can close this issue.
