### ISSUE TITLE
Thumbnails not requested

### ISSUE THREAD

**Issue by thomasroine** [gordon-matt/elFinder.NetCore#2]
What do I need to configure on the client side in order for the thumbnails to be requested? I never see the ?cmd=tmb in the url to the server.

**Comment by gordon-matt** [comment]
Solved. Thumbnails are now working.

**Comment by gordon-matt** [comment]
I may have spoken too soon - the thumbs do get generated and show fine the first time, but when trying to show existing thumbs (after refresh, for example), then there's an exception. I will look into this again as soon as I have the time. Can't promise when that will be.

**Comment by gordon-matt** [comment]
Solved.
