### ISSUE TITLE
Azure connector failure

### ISSUE THREAD

**Issue by ersatzDev** [gordon-matt/elFinder.NetCore#21]
Hi, 

Thanks for writing the asp.net connector and sample app. 

I'm getting errors when trying to use the azure storage connector.

On the front end
Invalid backend response. Error occurred on the serve side. HTTP error 500. 

On the back end I get the error below (json of exceptiondata from application insights). I've changed the the account and key in the startup.cs, the url in the index.cshml and also the root directory in the AzureStorageController.cs. 

Are there other configs I need to set? 

  "data": {
    "baseType": "ExceptionData",
    "baseData": {
      "ver": 2,
      "properties": {
        "DeveloperMode": "true",
        "AspNetCoreEnvironment": "Development"
      },
      "exceptions": [
        {
          "id": 1975337,
          "typeName": "System.Net.Http.HttpRequestException",
          "message": "An error occurred while sending the request.",
          "hasFullStack": true,
          "parsedStack": [
            {
              "level": 0,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 1,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 2,
              "method": "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 3,
              "method": "System.Net.Http.DiagnosticsHandler+<SendAsync>d__2.MoveNext",
              "assembly": "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
            }
          ]
        },
        {
          "id": 5978618,
          "outerId": 1975337,
          "typeName": "System.Net.Http.WinHttpException",
          "message": "The server name or address could not be resolved",
          "hasFullStack": true,
          "parsedStack": [
            {
              "level": 0,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 1,
              "method": "System.Threading.Tasks.RendezvousAwaitable`1.GetResult",
              "assembly": "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
            },
            {
              "level": 2,
              "method": "System.Net.Http.WinHttpHandler+<StartRequest>d__105.MoveNext",
              "assembly": "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
            }
          ]
        }
      ]
    }
  }

**Comment by gordon-matt** [comment]
@fsmirne Would you like to take a look? I don't have access to any Azure account to test this. Otherwise, this is open for anyone in the community who would like to help...

**Comment by fsmirne** [comment]
hey @ersatzDev,
From the error logs you posted, I don't think the message is coming from the AzureConnector code. It seems that the the Windows.Storage library is not able to connect to the storage endpoint. I'm basing this on the fact that the exception is being thrown is of type `System.Net.Http.WinHttpException` and the AzureStorage connector uses Microsoft's library exclusively as the middle man for any messaging.
The first thing I would check is that you can access your storage account and then maybe we can figure out which function is throwing the exception.

You can try the following code on a new application to see if you're able to connect to your azure storage account (where path is the path of your root directory in your Azure Storage share):

```
        public static CloudFileDirectory GetRootDirectoryReference(string path)
        {
            var storageAccount = new CloudStorageAccount(new Microsoft.WindowsAzure.Storage.Auth.StorageCredentials(AccountName, AccountKey), true);

            // Create a CloudFileClient object for credentialed access to File storage.
            var fileClient = storageAccount.CreateCloudFileClient();

            // Get a reference to the file share we created previously.

            var fileshare = fileClient.GetShareReference(GetRoot(path));

            // Get a reference to the root directory for the share.
            return fileshare.GetRootDirectoryReference();
        }
```

Let me know what you find out.
Thanks

**Comment by ersatzDev** [comment]
Hi Flavio, 

Thanks for looking at this. I've added your method to the HomeController.cs of this sample app because I already configured the storage account to allow its address.  

I'm calling your code from an action method (as below) and getting a result back from Azure with information about the 'test' directory, so connection to Azure doesn't seem to be the problem. 
```
public IActionResult GetRootDirectoryReference()
{
     var AccountName = _configuration.GetValue<string>("AzureAccount:name");
     var AccountKey = _configuration.GetValue<string>("AzureAccount:key");
     return Json(GetRootDirectoryReference("test", AccountName, AccountKey));
}

```
The call that fails from the front end is this: 
```
Request URL: http://localhost:52521/el-finder/azure-storage/connector?cmd=open&target=&init=1&tree=1&_=1544744520587
Request Method: GET
Status Code: 500 Internal Server Error
```

On the back end there seem to be three exceptions, all for GET AzureStorage/Connector 
```
      
     ....
       "ai.operation.name": "GET AzureStorage/Connector",
      
     Exceptions
       "id": 54450534,
          "typeName": "System.Net.Http.HttpRequestException",
          "message": "An error occurred while sending the request.",
       ...
          "id": 1403853,
          "outerId": 54450534,
          "typeName": "System.Net.Http.WinHttpException",
          "message": "The server name or address could not be resolved",
     ...
          "id": 43338215,
          "typeName": "Microsoft.WindowsAzure.Storage.StorageException",
          "message": "An error occurred while sending the request.",
```

Hoping this will give you more information to work with.

**Comment by ersatzDev** [comment]
I think the issue may be in the GetConnector() of AzureStorageController.cs. 

When the root variable is instantiated, shouldn't the ULRs for root directory and thumbnail directory point to azure storage instead of local paths? 

```
private Connector GetConnector()
        {
            var driver = new AzureStorageDriver();

            string absoluteUrl = UriHelper.BuildAbsolute(Request.Scheme, Request.Host);
            var uri = new Uri(absoluteUrl);

            string rootDirectory = "matters"; // TODO: Change this to the name of your own Azure file share.

            var root = new RootVolume(
                rootDirectory,
                $"http://{uri.Authority}/el-finder/azure-storage/files/{rootDirectory}/",
                $"http://{uri.Authority}/el-finder/azure-storage/thumb/",
                '/')
            {
                //IsReadOnly = !User.IsInRole("Administrators")
                IsReadOnly = false, // Can be readonly according to user's membership permission
                IsLocked = false, // If locked, files and directories cannot be deleted, renamed or moved
                Alias = "Files", // Beautiful name given to the root/home folder
                MaxUploadSizeInKb = 2048, // Limit imposed to user uploaded file <= 2048 KB
                //LockedFolders = new List<string>(new string[] { "Folder1" })
            };

            driver.AddRoot(root);

            return new Connector(driver);
        }
```
The actual failure happens when execution gets to line 323 of AzureStorageAPI.cs, the ListFilesAndDirectoriesAsync() method. 

` if (!await sampleDir.ExistsAsync()) return new IListFileItem[0];`

When I commented out that line above, connector went ahead and created a Files subdirectory in the "matters" container I specified in the GetConnector. The elFinder front end then mounted the newly created Files directory and I was able to upload a couple of images. The images show only azure storage but do not show in the elFinder manager, lots of "error while sending request" happening in the back end especially in the AzureStorageAPI.cs.

**Comment by fsmirne** [comment]
Hi @ersatzDev,

If the code I gave you is failing, then the problem is not in elfinder connector. This code is straight from the Microsoft Storage library.

I see that you set your root directory path to "matters". Do you have a file share called matters in Azure Storage? If your share is a blob share, this is not gonna work, only file shares.

Lastly, the only thing you need to set is the root directory path. Everything else will work with the configured routes in the sample code.

If can upload a reproducible code to GitHub, I can help debug it for you but the first thing you need to get working is the sample code from my previous message. If that doesn't work then the library is not finding your share.

**Comment by ersatzDev** [comment]
Hi Flavio, 

The code you posted runs successfully and gets a result back from Azure. However, the "matters" directory is actually a BLOB container and not a file share, so I guess what I'm trying to do won't work. 

What's interesting is that your code returned a result event if I pointed it to the blob container. 

Are there any plans for a BLOB connector in future?

**Comment by fsmirne** [comment]
Ahh. That explains a lot. To be honest, I haven't tried to connect to a BLOB share. I don't think it would be too hard to support it since the AzureStorage library does the heavy lifting of it.
I'll see if I can spend some time in the next few weeks and see how much work it would take. Once I figure it out, I will let you know on this issue page...

**Comment by ersatzDev** [comment]
Thank you, looking forward to it.

**Comment by fsmirne** [comment]
Hi @ersatzDev,

I just wanted to follow up on this. I did look at adding support for BlobStorage and it doesn't seem like it would be too hard, but it would be a little time consuming.

If you look at the sample code provided [here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet?tabs=windows), you can see that it's very similar to the code I wrote for File Storage. In fact, it seems like the library offers most of the same functions for both Files or Blobs. You just have to create the correct `Client` for the type of storage you're dealing with.

I think the next steps would be to replicate the code in AzureStorageAPI and make a Blob version. If you or anybody wants to take a crack at it, I can offer my help, but I don't have too much time to dedicate to that at the moment.

I hope this helps get you started. Let me know if there's anything I can do to help.
