### ISSUE TITLE
GetTargetsArray method should split on , instead of ;

### ISSUE THREAD

**Issue by thomasroine** [gordon-matt/elFinder.NetCore#3]
The GetTargetsArray doesnt work when you select multiple files to remove. The split method used in this function uses semicolon to split but should use comma. Should be like below. I'm not used to GIT so I could not fix it in a new branch and create pull request for it. Please fix in master.

`private IEnumerable<string> GetTargetsArray(HttpRequest request)
        {
            IEnumerable<string> targets = null;

            IDictionary<string, string> parameters = request.Query.Count > 0
                ? request.Query.ToDictionary(k => k.Key, v => string.Join(",", v.Value))
                : request.Form.ToDictionary(k => k.Key, v => string.Join(",", v.Value));

            if (targets == null)
            {
                string t = parameters.GetValueOrDefault("targets[]");
                if (string.IsNullOrEmpty(t))
                {
                    t = parameters.GetValueOrDefault("targets");
                }
                if (string.IsNullOrEmpty(t))
                {
                    return null;
                }
                targets = t.Split(',');
            }
            return targets;
        }`

**Comment by gordon-matt** [comment]
Thanks for your notes. I have fixed this and the other issues you opened.
