### ISSUE TITLE
Invalid backend response.

### ISSUE THREAD

**Issue by dmitry-web** [gordon-matt/elFinder.NetCore#31]
I'm getting 500 error, when resizing image and clicking **save as**, an empty file is created.
Exception occurs here https://github.com/gordon-matt/elFinder.NetCore/blob/master/elFinder.NetCore/Drivers/FileSystem/FileSystemDriver.cs#L316

https://i.imgur.com/occDEWn.png

**Comment by fsmirne** [comment]
I've added a fix for this issue in my fork and will send a pull request. We were not handling one of the new types of "Put" command which sends encoding as "scheme" (https://github.com/Studio-42/elFinder/wiki/Client-Server-API-2.1#put)

**Comment by gordon-matt** [comment]
@dmitry-web Note that a new version has been uploaded to NuGet.
