### ISSUE TITLE
Azure Storage Emulator Integration

### ISSUE THREAD

**Issue by frankely** [gordon-matt/elFinder.NetCore#34]
What would it take to make this able to be configured for the Azure Storage Emulator or Azurite so when running locally/development a Storage Account is not needed?

**Comment by gordon-matt** [comment]
Sounds like a great idea. I don't have access to Azure either. The Azure driver was created by @fsmirne. Due to the number of Azure specific issues being opened, I have requested that he move the Azure driver code to a separate repository.. at which point I suggest opening an issue there. I will leave it open here for the moment though.

**Comment by fsmirne** [comment]
@frankely I believe neither Azure Storage Emulator nor Azurite support File Shares, which is what we support in the Azure Storage driver. If that's the case, it would not be possible to integrate these products into it. There has been a couple requests to add support for Azure Blobs, but that hasn't been implemented yet so at the moment I'd have to say it's not possible.

**Comment by frankely** [comment]
@fsmirne thank you for replying with this, in my case because I'm using VS Code remote containers (docker-compose) I just need to add this little guy https://hub.docker.com/r/microsoft/azure-storage-emulator/ :) and I should be able to use it, hey @gordon-matt  that might be an option for you to since you don't havr access to Azure.

**Comment by frankely** [comment]
An alternative to this will be have a docker container running https://hub.docker.com/r/microsoft/azure-storage-emulator/ and just get a connection string for that. See link for more information.

**Comment by frankely** [comment]
I see @fsmirne, that was my first assumption, thank you for clarifying that!
