### ISSUE TITLE
onlyMimes is not supported (have workaround)

### ISSUE THREAD

**Issue by trannamtrung1st** [gordon-matt/elFinder.NetCore#35]
When I use "onlyMimes" in the client configuration, it says that the "mimeDetect" option in the Connector must be configured (specific value is "internal")
I have read about the "mimeDetect" option but it hasn't been developed yet. 
I have some workarounds on this, could I contribute my idea to your project?

Further technical details
.NET Core version: 3.1

**Comment by gordon-matt** [comment]
Of course, I welcome any contributions to the project. Once you've made the changes, please create a pull request, so I can review and test the changes before merging them.

**Comment by gordon-matt** [comment]
New version released
