### ISSUE TITLE
Crash "ls" function when uploading a non-standard Image file (have workaround)

### ISSUE THREAD

**Issue by trannamtrung1st** [gordon-matt/elFinder.NetCore#36]
I uploaded an image (.png) which was not in standard format and it thrown exception when calculating the Image Size --> the "ls" command request failed.
Related issue (System.Drawing): [https://stackoverflow.com/questions/14099246/system-drawing-parameter-is-not-valid](url)
___
Steps to reproduce:

1. Upload this image in a folder: https://i.ibb.co/nn0tyHp/banner.png
2. Request open that folder --> failure
___
Workaround:
`try`
`{`
`  var dim = volume.PictureEditor.ImageSize(stream);`
`  response = new ImageModel`
`  {`
`    Thumbnail = await volume.GenerateThumbHashAsync(file),`
`    Dimension = $"{dim.Width}x{dim.Height}"`
`  };`
`}`
`//catch for non standard images`
`catch (Exception)`
`{`
`  response = new FileModel();`
`}`
___
Further technical details
.NET Core version: 3.1

**Comment by gordon-matt** [comment]
Thank you. I will look into this.

**Comment by gordon-matt** [comment]
FYI - I just downloaded the image file and it's working perfectly fine for me.. I have tried refreshing it and even closing and opening the page.. but it's still fine. Are you sure that you linked to the correct file?

**Comment by trannamtrung1st** [comment]
So sorry, it seems like that site retouched my image.
This is the raw image on google drive (tested): 
https://drive.google.com/file/d/1_dImWN-kUKuXA6PM-ReyW6GIbiC6_yzd/view?usp=sharing

**Comment by gordon-matt** [comment]
Thank you. I have fixed this. It will be in the next release (soon).

**Comment by trannamtrung1st** [comment]
Thanks for your time. Look forward to the next release.

**Comment by gordon-matt** [comment]
New version released
