### ISSUE TITLE
Consider splitting Azure driver to separate repository

### ISSUE THREAD

**Issue by gordon-matt** [gordon-matt/elFinder.NetCore#37]
@fsmirne I've gotten quite a few issues raised that are specific to Azure.. including one open at the moment. I'm wondering if we can make things easier for both of us if you keep the code for the Azure driver in a separate repository. That way, issues for the Azure driver can be directed to you more easily, while I deal with issues relating to the core project. This would probably be better, especially if someone decided to create another driver for some other online storage, like Google Cloud or whatever. I think having links to each driver in the README would be better than keeping the code and issues for all of them in this one repo. What do you think?

**Comment by fsmirne** [comment]
I like that idea. It would be easier to add features, etc. I also don't get notified when new issues are opened here so that would solve that problem.
Is there a way to transfer your nuget package to me so we don't lose all the versions, upgrades, etc?

**Comment by frankely** [comment]
That'll be cool! I am waiting for this since I want to propose a few changes to that library. Let me know if you need any help with this.

**Comment by gordon-matt** [comment]
@fsmirne It looks like I can indeed add you as an additional package owner: https://devblogs.microsoft.com/nuget/managing-package-owners/.

So I will do that soon. I think I will need your username on NuGet though. Please provide that.

In the meantime, could you have a look at pull request #38 ? I have implemented that a few minutes ago, but it only works for the file system driver. I wanted to give you a chance to implement the same for the Azure driver if you want.. before I release the new versions.

**Comment by fsmirne** [comment]
Awesome! I'm not sure if it will be easy to preserve history on github. I'm debating whether I should create a new repository or if there's another way to keep everything when I migrate to the new split repository. I'll investigate. In the meantime, here's my nuget username: fsmirne.

I'll take a look at request #38 and will let you know what's the best way to proceed.
Thanks

**Comment by fsmirne** [comment]
BTW, I added the features from #38 to AzureConnector, added some fixes I found along the way and sent a pull request with the changes.

**Comment by gordon-matt** [comment]
@fsmirne Okay I bumped the numbers to 1.3.1, added you as a package owner for the Azure one and have only uploaded the main package. See if you can release the Azure package now yourself.

**Comment by fsmirne** [comment]
@gordon-matt I just published the new version. It's still validating. Hopefully it will work without any hiccups. If everything works ok, I will create a new repository tomorrow and migrating everything over.

**Comment by gordon-matt** [comment]
@fsmirne Yes, I see it now. Nice!

**Comment by fsmirne** [comment]
All done. new repository is at [elFinder.NetCore.AzureStorage](https://github.com/fsmirne/elFinder.NetCore.AzureStorage)

**Comment by gordon-matt** [comment]
@fsmirne Nice. Thank you.
