### ISSUE TITLE
"onlyMimes" option should be able to display all files belong to a type

### ISSUE THREAD

**Issue by trannamtrung1st** [gordon-matt/elFinder.NetCore#41]
According to: https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1#onlyMimes
"onlyMimes" should support both "type" and "type/subtype". e.g: image, image/jpeg
I implemented this in https://github.com/gordon-matt/elFinder.NetCore/pull/38, but it seems that it is missed in the lastest release when I tested it (version 1.3.1). 
I has created a new one here: https://github.com/gordon-matt/elFinder.NetCore/pull/40
Sorry for being late in review but this is a quite important feature.

**Comment by gordon-matt** [comment]
Yes, I did see your pull request and I will make the change. I am just very busy working on many projects right now. I will try to come back to this soon. Dung lo lang nhe!  ;-)

**Comment by trannamtrung1st** [comment]
It's not urgent, I can still use the source version for my needs. Thanks for taking your time.  👍 👍

**Comment by gordon-matt** [comment]
Done. See new version on NuGet
