### ISSUE TITLE
Lib folder missing

### ISSUE THREAD

**Issue by aqkhana2002** [gordon-matt/elFinder.NetCore#44]
where is lib folder ? even I have installed a package.

**Comment by gordon-matt** [comment]
If you are talking about the client side packages, they are specified in libman.json. If you are using Visual Studio, just right-click libman.json and choose, "Restore Client-Side Libraries". More info: https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-vs?view=aspnetcore-3.1#restore-library-files
