### ISSUE TITLE
Integrate to Angular Asp.net Core app, The volume root statuses requires volumeid property

### ISSUE THREAD

**Issue by jonatmoy** [gordon-matt/elFinder.NetCore#45]
Hello, I am trying to integrate your connector into my angular 9 + .net core 3.1 application. What should we do to configure the connector? I always get "error from backend"from the front and "elfinder debug: [warning] [elfinder] The volume root statuses requires `volumeid` property" from the back

**Comment by jonatmoy** [comment]
https://stackoverflow.com/questions/62320015/unable-to-integrate-elfinder-in-angular-project/62770531#62770531

**Comment by gordon-matt** [comment]
Glad to see you solved it and I appreciate the link to the solution. Hope it helps others.
