### ISSUE TITLE
Integrate the search command

### ISSUE THREAD

**Issue by jonatmoy** [gordon-matt/elFinder.NetCore#46]
Hello, I would like to integrate a search bar in elfinder I saw that this had not yet been implemented in your connector. Do you think you will ever do it?

**Comment by gordon-matt** [comment]
Not likely any time soon, as I have numerous projects going on and I don't particularly need this feature myself. However, it would be something nice to have. If you implement it yourself, feel free to raise a PR and I will review and merge your code.

**Comment by jonatmoy** [comment]
ok I will try but I do not understand much about your code I do not promise anything. Anyway, great job, thank you very much!

**Comment by mohdimran043** [comment]
Any update on search feature ?. I am trying to enable the button but it disappears immediately after load!..

**Comment by gordon-matt** [comment]
Get latest NuGet package (v1.3.4). Many thanks to @mguinness
