### ISSUE TITLE
upload not working

### ISSUE THREAD

**Issue by maccarilab** [gordon-matt/elFinder.NetCore#49]
Hi,  
I tried some functions with the solution as download, copy/delete file, open/edit file, create folder: there aren't problems.
Now I'm trying to upload file and the application goes in crash/freeze. I must kill 'Visual Studio'.
In debugger I have upload -> GetConnector -> connector ( case ls ) -> ProcessAsync -> crash/freeze 
Probably I missed some parameters. The folder 'Files' has write permissions.
Can you help me?
Thanks
Sergio

**Comment by trannamtrung1st** [comment]
Hi Sergio, can you provide more detail information such as what file you are trying to upload and the stack trace?
You can clone this repository and debug into the ProcessAsync function for more detail information of the crash.

**Comment by maccarilab** [comment]
Hi, probably I missed some parameters. Unfortunately there is a php documentation but not for dot net core c#.
I'm not sure that "customData: { folder: '../Files' }," is correct.

Some details:
**FileSystemController.cs**
        private Connector GetConnector()
        {
            var driver = new FileSystemDriver();
            string absoluteUrl = UriHelper.BuildAbsolute(Request.Scheme, Request.Host);
            var uri = new Uri(absoluteUrl);
                    var root = new RootVolume(
                    Startup.MapPath("~/Files"),
                    $"{uri.Scheme}://{uri.Authority}/Files/",
                    $"{uri.Scheme}://{uri.Authority}/el-finder/file-system/thumb/")
                    {                        
                        //IsReadOnly = !User.IsInRole("Administrators"),
                        IsReadOnly = false, // Can be readonly according to user's membership permission
                        IsLocked = false, // If locked, files and directories cannot be deleted, renamed or moved
                        Alias = "Files", // Beautiful name given to the root/home folder
                        MaxUploadSizeInKb = 2048, // Limit imposed to user uploaded file <= 2048 KB
                        //LockedFolders = new List<string>(new string[] { "Folder1" })
                    };
                    driver.AddRoot(root);       
            return new Connector(driver)
            {
                // This allows support for the "onlyMimes" option on the client.
                MimeDetect = MimeDetectOption.Internal
            };
        }
**Index.cshtml**
@section scripts {
    <script type="text/javascript">
		// Documentation for client options:
		// https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
        $(document).ready(function () {
            var myCommands = elFinder.prototype._options.commands;
            var disabled = ['callback', 'chmod', 'editor', 'netmount', 'ping', 'search', 'zipdl', 'help']; // Not yet implemented commands in elFinder.NetCore
            elFinder.prototype.i18.en.messages.TextArea = "Edit";
            $.each(disabled, function (i, cmd) {
                (idx = $.inArray(cmd, myCommands)) !== -1 && myCommands.splice(idx, 1);
            });
            var options = {
                url: '/el-finder/file-system/connector', // Default (Local File System)
                customData: { folder: '../Files' },
                @*//customData: { folder: '@Model.Folder', subFolder: '@Model.SubFolder' }, // customData passed in every request to the connector as query strings. These values are used in FileController's Index method.*@
                rememberLastDir: false, // Prevent elFinder saving in the Browser LocalStorage the last visited directory
                commands: myCommands,
                //lang: 'pt_BR', // elFinder supports UI and messages localization. Check the folder Content\elfinder\js\i18n for all available languages. Be sure to include the corresponding .js file(s) in the JavaScript bundle.
                uiOptions: { // UI buttons available to the user
                    toolbar: [
                        ['back', 'forward'],
                        ['reload'],
                        ['home', 'up'],
                        ['mkdir', 'mkfile', 'upload'],
                        ['open', 'download'],
                        ['undo', 'redo'],
                        ['info'],
                        ['quicklook'],
                        ['copy', 'cut', 'paste'],
                        ['rm'],
                        ['duplicate', 'rename', 'edit'],
                        ['selectall', 'selectnone', 'selectinvert'],
                        ['view', 'sort']
                    ]
                },
               // onlyMimes: ["image", "text/plain"]  Get files of requested mime types only
                //lang: 'vi', // Change language
            };
            $('#elfinder').elfinder(options).elfinder('instance');
        });
    </script>
**DEBUGGER**
**path  ( connector.cs  case "ls")**
{elFinder.NetCore.FullPath}
    Directory: {elFinder.NetCore.Drivers.FileSystem.FileSystemDirectory}
    File: null
    HashedTarget: "v1_RmlsZXM1"
    IsDirectory: true
    IsRoot: false
    RelativePath: ""
    RootVolume: {elFinder.NetCore.RootVolume}

**item** ( before going to freeze )
{elFinder.NetCore.RootVolume}
    Alias: "Files"
    DirectorySeparatorChar: 92 '\\'
    IsLocked: false
    IsReadOnly: false
    IsShowOnly: false
    LockedFolders: null
    MaxUploadSize: 2097152
    MaxUploadSizeInKb: 2048
    MaxUploadSizeInMb: 2
    PictureEditor: {elFinder.NetCore.Drawing.DefaultPictureEditor}
    RootDirectory: "C:\\Sergio\\VS2019\\ElFinderDemo\\elFinder.NetCore.Web\\wwwroot\\Files"
    StartDirectory: null
    ThumbnailDirectory: "C:\\Sergio\\VS2019\\ElFinderDemo\\elFinder.NetCore.Web\\wwwroot\\Files\\.tmb"
    ThumbnailSize: 48
    ThumbnailUrl: "https://localhost:44338/el-finder/file-system/thumb/"
    UploadOverwrite: true
    Url: "https://localhost:44338/Files/"
    VolumeId: null

I'M GOING TO CLONE AGAIN THE SOLUTION SO WE WILL HAVE THE SAME SOLUTION VERSION.
THANKS

**Comment by maccarilab** [comment]
I cloned again the solution. I installed bootstrap again ( during the cloning some file are not copied ) and now I have a different graphic version. The upload is correct.
We can close the issue.
Best regards.

![UploadOK](https://user-images.githubusercontent.com/67383364/97637399-df32b600-1a3a-11eb-90b5-fa8bec03ff0c.png)
