### ISSUE TITLE
ConvertThumbnailExtension must return mime type

### ISSUE THREAD

**Issue by thomasroine** [gordon-matt/elFinder.NetCore#5]
The method 
`ConvertThumbnailExtension(string originalImageExtension)`
in DefualtPicturesEditor must return correct mimetype. As is it now it returns .jpg for .jpg files but it must return "image/.jpeg". See below. If not this statement throws an exception:
`return new FileStreamResult(thumb.ImageStream, thumb.MimeType);`
It is the FileStreamResult constructor that complains about it cant recognize ".jpg". I guess this is something that has changed in .net core.

Please change the code to this:
`        public string ConvertThumbnailExtension(string originalImageExtension)
        {
            string ext = originalImageExtension.ToLower();
            if (ext == ".tiff")
            {
                return "image/png";
            }

            switch (ext)
            {
                case ".png":
                    return "image/png";
                case ".jpg":
                    return "image/jpeg";
                case ".jpeg":
                    return "image/jpeg";
                case ".gif":
                    return "image/gif";
                default:
                    throw new ArgumentException(typeof(DefaultPicturesEditor).FullName + " does not support thumbnails for '" + originalImageExtension + "' files.");
            }
        }`

**Comment by gordon-matt** [comment]
Hi and thanks for your comment. I'm not the author of the original code - I merely migrated it to .NET Core and did some refactoring on it. However, I just took a look and I think you're probably having an issue in **Root.cs**, in `GenerateThumbnail()`, right? Well, the answer would be to do the same there as what's done in **Connector.cs** in `GetThumbnail()`, which is to convert the extension to a mime type using `Utils.GetMimeType()`, which you can see on line 278. I will make the modification for you.

**Comment by gordon-matt** [comment]
Solved.
