### ISSUE TITLE
FOLDER/FILE SHARING

### ISSUE THREAD

**Issue by maccarilab** [gordon-matt/elFinder.NetCore#51]
Hi, is it possible to share some file in ElFinder and organize folders for sharing?
Thanks in advance.
Sergio

**Comment by gordon-matt** [comment]
Can you please explain in more detail what you want?

**Comment by maccarilab** [comment]
Hi,
I'm using User.Identity.Name for private access. I wonder if there is a possibility to organize a share, admin user of course, as in the image. 
![Share](https://user-images.githubusercontent.com/67383364/97691533-c3f99200-1a9e-11eb-9bd9-759d16cafed1.png)

**Comment by gordon-matt** [comment]
Sorry about the late reply.. I am extremely busy these days...

Anyway, I don't think there is an option for exactly what you want.. But I guess you can probably just change the root folder based on the user. I have not tried this, but you could probably do the following:

Open the `FileSystemController` in `elFinder.NetCore.Web` (or in your own app) and then find this:

```
var root = new RootVolume(
	Startup.MapPath("~/Files"),
	$"{uri.Scheme}://{uri.Authority}/Files/",
	$"{uri.Scheme}://{uri.Authority}/el-finder/file-system/thumb/")
{
	//IsReadOnly = !User.IsInRole("Administrators")
	IsReadOnly = false, // Can be readonly according to user's membership permission
	IsLocked = false, // If locked, files and directories cannot be deleted, renamed or moved
	Alias = "Files", // Beautiful name given to the root/home folder
	//MaxUploadSizeInKb = 2048, // Limit imposed to user uploaded file <= 2048 KB
	//LockedFolders = new List<string>(new string[] { "Folder1" })
};
```

And change it to this:

```
var root = new RootVolume(
	Startup.MapPath($"~/Files/{User.Identity.Name}"),
	$"{uri.Scheme}://{uri.Authority}/Files/{User.Identity.Name}/",
	$"{uri.Scheme}://{uri.Authority}/el-finder/file-system/thumb/")
{
	//IsReadOnly = !User.IsInRole("Administrators")
	IsReadOnly = false, // Can be readonly according to user's membership permission
	IsLocked = false, // If locked, files and directories cannot be deleted, renamed or moved
	Alias = $"Files for {User.Identity.Name}", // Beautiful name given to the root/home folder
	//MaxUploadSizeInKb = 2048, // Limit imposed to user uploaded file <= 2048 KB
	//LockedFolders = new List<string>(new string[] { "Folder1" })
};
```

Other than that, I'm not sure what to suggest. If it works as you expect, please comment back here.

Good luck

**Comment by maccarilab** [comment]
Thank you, I will try and I will let you know.
Sergio
