### ISSUE TITLE
ElFinder.NetCore on Linux

### ISSUE THREAD

**Issue by maccarilab** [gordon-matt/elFinder.NetCore#52]
Hi, I'm going to install a web application dot net core having ElFinder on Linux. My code is like this
                switch (FilesUtente)
                {
                    case ("adminfs"):
                        var rootAdmin = new RootVolume(
                        Startup.MapPath("~/FilesPrivate"),
                        $"{uri.Scheme}://{uri.Authority}/FilesPrivate/",
                        $"{uri.Scheme}://{uri.Authority}/el-finder/file-system/thumb/")
In Windows IIS is ok. Do you know if I must change mapping for Linux file system?
Best regards.
Sergio

**Comment by maccarilab** [comment]
Test Linux OK!
Best regards
Sergio

**Comment by gordon-matt** [comment]
It's good to know it works fine on Linux. Thanks for letting us know.
