### ISSUE TITLE
missing lib directory

### ISSUE THREAD

**Issue by benny-adiwijaya** [gordon-matt/elFinder.NetCore#58]
when I try to run demo project i got 404 not found on lib directory, where i can find those files?

**Comment by trannamtrung1st** [comment]
If I remember properly, use the **Libman** to manage client library packages. Open **VisualStudio**, in the **Solution Explorer**, right click on the project and select **Restore Client-Side Libraries** --> the packages listed in file **libman.json** will be downloaded.
Reference: https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-vs?view=aspnetcore-5.0

**Comment by benny-adiwijaya** [comment]
Thank you

**Comment by hdsali** [comment]
Thank you So much.
