### ISSUE TITLE
unable to rename folder

### ISSUE THREAD

**Issue by dtraykov** [gordon-matt/elFinder.NetCore#6]
I've this problem when I try to rename a folder
![folderrename](https://user-images.githubusercontent.com/3616622/36852936-bd0c4e20-1d75-11e8-879e-ddefa48ccd9d.png)

**Comment by gordon-matt** [comment]
Please check again whether it's actually the rename function that is causing you problems, because I just tried it and not getting any errors. Also, the message in your screenshot says it's for the "Close" command. If you find out what's actually causing that message, let me know and I will take another look.

**Comment by dtraykov** [comment]
When I click on a folder in the directory tree, the rename button is disabled. Then, I click on the same folder in the tree a second time and the button becomes enabled. However, If I now click the rename button, an error occurs. I want to emphasize that this error occurs only when I try to rename a folder by selecting it through the directory tree.

```
elfinder.full.js Line: 26530

if (!file || !node.length) {
	return dfrd.reject('errCmdParams', this.title);
}

file : {…}
  dirs : 0
  hash : "v1_XE5ld0ZvbGRlcg2"
  locked : 0
  mime : "directory"
  name : "NewFolder"
  phash : "v1_RmlsZXM1"
  read : 1
  size : 0
  ts : 1519971338
  write : 1

this.title = "Rename"
node.length = 0
```

![folderrename1](https://user-images.githubusercontent.com/3616622/36889376-5c4132d0-1e02-11e8-95b9-03d60223948a.png)

**Comment by gordon-matt** [comment]
Sorry about the late response.. been busy. Had a quick look at this and yes, I can reproduce it now. However, when inspecting the Network tab in the browser's developer tools, I can see there is nothing being sent from browser to server. This means it's something to do with elFinder itself and not the connector. So I would suggest opening an issue on the [elFinder](https://github.com/Studio-42/elFinder) project instead.
