### ISSUE TITLE
Does we follow any connector design specification?

### ISSUE THREAD

**Issue by trannamtrung1st** [gordon-matt/elFinder.NetCore#60]
I want to add some new functions to the connector (mostly with the driver configuration, permissions, etc.). I wonder if we have any reference or documents? For example, https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1.
It seems that we didn't follow the original one.

**Comment by gordon-matt** [comment]
The link you posted would be the correct and only documentation we have to use.
