### ISSUE TITLE
Download folder

### ISSUE THREAD

**Issue by benny-adiwijaya** [gordon-matt/elFinder.NetCore#64]
Hi,

Is it possible to enable download folder in this project?

**Comment by trannamtrung1st** [comment]
It is possible via the disabled "zipdl" command in the sample project. However it is not implemented yet in the backend. Maybe you want to give it a try then create a pull request to this repo 👍.

**Comment by gordon-matt** [comment]
This would be a nice feature to have.

@trannamtrung1st By the way.. thanks for your support providing answers for many of the issues. I am so very busy, so I appreciate that you have taken time to do that. Cam on ban nhieu lam  ;-)

**Comment by gordon-matt** [comment]
1.3.6 Released on NuGet
