### ISSUE TITLE
elfinder installation

### ISSUE THREAD

**Issue by hdsali** [gordon-matt/elFinder.NetCore#65]
Hello,

I download the code and run it without errors.
but it just opens a page in my firefox browser, comparing to the elFinder php version, this ASP.net core looks like has a problem.
could you please help me how to run/install/config it to run looks like the php version of elFinder ?

thank you in advance

I attached an image of it.
![elFinder](https://user-images.githubusercontent.com/8676122/118513419-edcb8b00-b748-11eb-9be9-d50a1ac87912.jpg)

**Comment by trannamtrung1st** [comment]
Please refer to issue [#58](https://github.com/gordon-matt/elFinder.NetCore/issues/58)

**Comment by hdsali** [comment]
Thank you very much
