### ISSUE TITLE
Are there any option to prevent user upload file with given list of extensions ?

### ISSUE THREAD

**Issue by lengockyquang** [gordon-matt/elFinder.NetCore#69]
Hi everyone, are there any options to configure elfinder only accept some extension when user upload ?
I'm using elfinder.min.js version 2.1.49

**Comment by trannamtrung1st** [comment]
Hi, does this setting in elFinder client achieve what you want?
https://github.com/gordon-matt/elFinder.NetCore/blob/633da9a4d7d5c9baefd1730ee51bf7af54889600/elFinder.NetCore.Web/Views/FileManager/Index.cshtml#L45

**Comment by gordon-matt** [comment]
@trannamtrung1st I think maybe we need to implement some more options in root (RootVolume.cs), like `uploadDeny` and `uploadAllow`. See here: https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#uploadAllow

**Comment by gordon-matt** [comment]
More info: https://github.com/Studio-42/elFinder/issues/3007

**Comment by lengockyquang** [comment]
> Hi, does this setting in elFinder client achieve what you want?
> 
> https://github.com/gordon-matt/elFinder.NetCore/blob/633da9a4d7d5c9baefd1730ee51bf7af54889600/elFinder.NetCore.Web/Views/FileManager/Index.cshtml#L45

onlyMimes config just allow file manager to display files with allowed mime types. In fact, user can still upload inapproriate files through it

**Comment by trannamtrung1st** [comment]
I just created a pull request to support the 3 options: UploadOrder, UploadAllow, UploadDeny. Take a look when you have time @gordon-matt. :D

**Comment by gordon-matt** [comment]
@trannamtrung1st You are a fast worker, friend. I am glad you have time to help with this project. I will try to find time to review your code ASAP.

**Comment by gordon-matt** [comment]
1.3.6 Released on NuGet
