### ISSUE TITLE
Will this project be migrated to use ASP.NET Core 8?

### ISSUE THREAD

**Issue by utilsites** [gordon-matt/elFinder.NetCore#74]
Will this project be migrated to use ASP.NET Core 8?
I can try but I may not have the necessary knowledge.
It's a nice project and a very needed functionality.

**Comment by utilsites** [comment]
Migrated to ASP.NET 8 Core with success, added [pull request](https://github.com/gordon-matt/elFinder.NetCore/pull/75), @gordon-matt please accept it, if it's ok for you.
Thanks

**Comment by gordon-matt** [comment]
I've migrated to ASP.NET 8 in the develop branch yesterday. Please use that branch when submitting any further PRs.
