### ISSUE TITLE
Resize image and others broken features

### ISSUE THREAD

**Issue by bosusites** [gordon-matt/elFinder.NetCore#80]
On the migration to .NET 8 on 52b82128e825a894f9e210d0db26263c3df18c2a commit, some functionalities broke from concurrent calls to the same file. This is caused by miss usage of using. File access need to be closed before opened again.

Another thing is that this error reveals full path for the file being access. This is a security concern being a "Path Disclosure" vulnerability. Fixing the mentioned features, would not reveal the full path anymore. Although, for a more future proof solution, I would suggest implementing some kind of error message validation, making sure this kind of information is not sent to the user.

**Comment by gordon-matt** [comment]
Thanks. Good thing it's just the develop branch and not a release yet.

**Comment by gordon-matt** [comment]
Fixed
