### ISSUE TITLE
Dependabot Updates/Upgrades

### ISSUE THREAD

**Issue by rolan18** [gordon-matt/elFinder.NetCore#86]
Hi,  
When I run elFinder.NetCore through an analyzer, there are two high severity alerts associated with the current version of the SixLabors.ImageSharp library.  The fix for the CVEs is to just upgrade the package version.
Any chance the dependabot upgrade PR that handles that issue could be merged?

Many thanks

**Comment by gordon-matt** [comment]
Updated in version 1.4.1. It should show up in NuGet soon

**Comment by rolan18** [comment]
Many thanks!
